apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app.kubernetes.io/name: deploy

spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deploy

    spec:
      containers:
        - name: nginx
          image: nginx:2
