apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  labels:
    app.kubernetes.io/project: daemon
spec:
  matchLabels:
    labels:
      app.kubernetes.io/project: daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/project: daemon
    spec:
      containers:
        - name:  
