apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis

spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: redis

  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis

    spec:
      containers:
        - name: redis
          image: redis:alpine
